### ISSUE TITLE
URI in Readme contains 2 typos

### ISSUE THREAD

**Issue by jvandermeulen** [candy-chat/onlineUsersPlugin#1]
OnlineUsers Plugin Readme should contain URI that respects uppercase, besides that open should be replaced by online.
It should be http://yourserver:9090/plugins/onlineUsers (instead of ../plugins/openusers)

**Comment by mweibel** [comment]
Uh, openusers is wrong, I'll correct that.
But the URL is "plugins/onlineusers", because openfire does somehow lowercase the URL..
I'll fix that.
