### ISSUE TITLE
Unable to login through curl for accessing onlineusers plugin

### ISSUE THREAD

**Issue by mayursnarole** [candy-chat/onlineUsersPlugin#3]
Hi,
I want to access onlineusers plugin through php code using curl but I am not able to do this stuff. Can anybody help me.

Thanks in advance.
Mayur Narole

**Comment by mweibel** [comment]
But accessing with the web browser works?

**Comment by mayursnarole** [comment]
Yes.. It is accessing through browser but I want to access it through php code.. Is it possible??

**Comment by mweibel** [comment]
Sure. Can you show us the code you're using & the error you get?

Am 05.08.2013 um 06:57 schrieb mayursnarole notifications@github.com:

**Comment by mayursnarole** [comment]
Here is my code of php. For security reasons I am not able to give you hostname.

$submit_url = "http://example.com/plugins/onlineusers/list";

```
            $curl = curl_init();

            curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC ) ;
            curl_setopt($curl, CURLOPT_USERPWD, "EXAMPLEUSER:EXAMPLEPW");
            curl_setopt($curl, CURLOPT_HEADER, true);
            curl_setopt($curl, CURLOPT_POST, true);
            curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
            curl_setopt($curl, CURLOPT_POSTFIELDS, 'username=EXAMPLEUSER&password=EXAMPLEPW' );
            curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($curl, CURLOPT_HTTPHEADER, array('Accept: Application/json'));
            curl_setopt($curl, CURLOPT_USERAGENT, "Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0)");
            curl_setopt($curl, CURLOPT_REFERER, "http://example.com/plugins/onlineusers/list");
            curl_setopt($curl, CURLOPT_URL, $submit_url);

            echo curl_exec($curl);
            curl_close($curl);
```

Error : HTTP/1.1 302 Found Expires: Thu, 01 Jan 1970 00:00:00 GMT Set-Cookie: JSESSIONID=1k4tow3ci9ory;Path=/ Location: http://example.com/login.jsp?url=%2Fplugins%2Fonlineusers%2Flist Content-Length: 0

I am not able to login to openfire through this code. It is redirecting me to login.jsp page. 
Please suggest me the required changes.

**Comment by mweibel** [comment]
Please take a look at the readme.html:

```
# Settings

If the list of online users should be public (no admin authentication needed), add the following setting to your
system properties in the admin console:

plugin.onlineUsers.list.disableAuth = true
```

If you don't want to do this, you need first to login on the login.jsp site and afterwards with the cookies go to the online users page. 

Btw. I edited your code in order to not have your username/pw combination there as well...

**Comment by mayursnarole** [comment]
Thanks for your response. I got the answer...

**Comment by mayursnarole** [comment]
Hi,
Can we update plugin which will return result in xml format??

**Comment by mweibel** [comment]
Feel free to fork it and change it on your own.

**Comment by mayursnarole** [comment]
Thank you so much for your great time and response.. :-)
