### ISSUE TITLE
nice plugin it seems like the online status is not realtime

### ISSUE THREAD

**Issue by yasirmturk** [candy-chat/onlineUsersPlugin#5]
user online few hours ago are returned in the list too? there should be a param to adjust the online time ..

**Comment by mweibel** [comment]
This is defined by Openfire as far as I remember.

**Comment by yasirmturk** [comment]
nops the list surely differs from the presence status fetched by using xmpp

**Comment by mweibel** [comment]
https://github.com/candy-chat/onlineUsersPlugin/blob/master/src/java/com/amiadogroup/openfire/onlineUsers/OnlineUsersServlet.java#L119

it does use Openfire's session manager, therefore it is defined by openfire (obviously), the plugin just reads whatever openfire reports.
